name: prefect_tryout
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pyarrow
    - polars
    - duckdb
    - dbt-duckdb
    - prefect
    - ipykernel
    - jupyter
    - deltalake
    - seaborn
    - matplotlib
